name: Clean Discord Notifications
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, closed, merged]
  create:
  delete:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {
              "embeds": [
                {
                  "title": "Repository Activity: ${{ github.event_name }}",
                  "description": "${{ formatEventDescription() }}",
                  "color": ${{ getEventColor() }},
                  "fields": [
                    ${{ getEventFields() }}
                  ],
                  "timestamp": "${{ github.event.head_commit.timestamp || now() }}"
                }
              ]
            }
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
